# Generated by Django 4.2.7 on 2023-11-26 18:30

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("dob", models.DateField(null=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ImageField(
                        default="employees/employeeee.png",
                        null=True,
                        upload_to=mainapp.models.unique_img_name,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
