# Generated by Django 4.2.7 on 2023-11-30 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donor",
            old_name="salary",
            new_name="donation",
        ),
    ]
