# Generated by Django 4.2.7 on 2023-11-28 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_subscribedusers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubscribedUsers",
        ),
    ]
